# Rust M3U8 下载器配置文件示例

# 1. 通用系统配置
[system]
# 1.1 并发下载数量，程序默认20
workers = 20
# 1.2 失败重试次数（0表示无限重试，程序默认3）
retry = 3
# 1.3 代理池，配置方式为：`[地址, 权重]` 下载时按照权重分配，程序默认不开启（使用系统网络环境），示例：
#    proxies = [
#        ["http://127.0.0.1:7890", 100],
#        ["http://127.0.0.1:7891", 50],
#    ]
#    公共代理：https://proxy.scdn.io/
proxies = []
# 1.4 日志等级：trace, debug, info(默认), warn, error
log_level = "trace"
# 1.5 ts地址的基础url，当ts连接不是绝对url时需要启用，程序默认不指定
# base_url = ""

# 2. HTTP请求头配置，程序默认值如下
[headers]
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
Accept = "*/*"
Accept-Encoding = "gzip, deflate, br"
Connection = "keep-alive"

# 3. 广告过滤配置
[filters]
# 3.1 URL匹配正则表达式列表，示例（默认为空）:
#    url_patterns = [
#        "ad\\.example\\.com",
#        ".*_ad\\.ts"
#    ]
url_patterns = []
# 3.2 分辨率匹配，取true时仅保留分辨率出现频次最高的视频片段，移除其它分辨率片段，默认不开启
resolution = false